import Footer                 from "@/components/layout/footer"
import Header                 from "@/components/layout/header"
import tw                     from "@/utils/tw"
import type { Metadata }      from "next"
import { SessionProvider }    from "next-auth/react"
import { Lora, Merriweather } from "next/font/google"
import "./globals.css"
import { ReactNode }          from "react"

const lora = Lora({
                      variable: "--font-lora",
                      subsets: [ "latin" ],
                      display: "swap",
                      preload: true,
                  })

const merriWeather = Merriweather({
                                      weight: [ "300", "400", "700", "900" ],
                                      display: "swap",
                                      style: [ "normal", "italic" ],
                                      variable: "--font-merriWeather",
                                      subsets: [ "latin" ],
                                      preload: true,
                                  })

export const metadata: Metadata = {
    title: {
        default: "Sentinel of Liberty",
        template: "%s | Sentinel of Liberty",
    },
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode
}>) {
    const bodyStyles = tw`${ lora.variable } ${ merriWeather.variable } h-full antialiased`
    
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={ bodyStyles }>
                <SessionProvider>
                    <Header />
                    { children }
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    )
}
