name: sentinel-of-liberty

services:
  sentinel-of-liberty_elasticsearch:
    image: 'elasticsearch:9.1.2'
    container_name: 'sentinel-of-liberty_elasticsearch'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=j@rV1s
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - sentinel-of-liberty_network

  sentinel-of-liberty_database:
    image: 'postgres:latest'
    container_name: 'sentinel-of-liberty_database'
    restart: 'on-failure'
    environment:
      POSTGRES_DB: sentinel-of-liberty_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sentinel-of-liberty_network
    links:
      - sentinel-of-liberty_elasticsearch
    depends_on:
      - sentinel-of-liberty_elasticsearch
volumes:
  pgdata:
    driver: local

networks:
  sentinel-of-liberty_network:
    driver: bridge
